import time
a = 0
b = 0
print('First Homework')
print('')
print('Task 1')
print('')
print('Define variables a and b. Read values a and b from console and calculate:') 
print('1)a + b')
print('2)a - b')
print('3)a * b')
print('4)a / b.') 
print('And output obtained results.')
print('')
print('--------------------------------')
print('               A                ')
print('Now "a"=',a)
print('Please enter "a" =>')
a = int(input())
print('And now "a"=',a)
print('')
print('--------------------------------')
print('               B                ')
print('Now "b"=',b)
print('Please enter "b" =>')
b = int(input())
print('And now "b"=',b)
print('')
print('--------------------------------')
print('         Body of my Homework    ')
print('')
print('The first my function is +;result => ', a + b)
print('The second my function is -;result => ', a - b)
print('The third my function is *;result => ', a * b)
if a == 0 or b == 0:
    print('"a" or "b" = 0, please reboot this program and write any nubers who != 0')
   # quit()
    print('')
else:
    print('The fourth my function is /;result => ', a / b)
    print('')
print('--------------------------------')
print('Task 2')
print('')
print('Output question “What is your name?“, “How old are you?“, Where do you live?“.')
print('Read the answer of user and output next information:')
print('“Hello, (answer(name))“')
print('“Your age is  (answer(age))“')
print('“You live in  (answer(city))“')
print('')
print('----------------------------------')
print('               Name                ')
print('Please enter your name(use only A-Z,a-z,A-Я,а-я):')
#if name > 15:
#    print('Use 0 - 15 chasters in name')
#else:
name = str(input())
print('')
print('----------------------------------')
print('               Age                ')
print('Please enter your age(use only 0 - 110):')
age = int(input())
print('')
if age <  0 or age > 110:
    print('You write incorrect age,please reboot this program and try again(use only 0 - 110)')
    quit()
else:
   print('Please enter your city (use only A-Z,a-z,A-Я,а-я):')
   city = str(input())
   print('')
print('Choise varints to giving information to you: 1- in the string; 2- in the column ')
choise = int(input())
print('')
print('Error checking...')
time.sleep(3)
print('')
if choise <= 0 or choise >= 3:
    print('You write incorrect number of choise,please reboot this program and try again(use only 1 or 2)')
    quit()
else:
    print ('You choise is сorrect')
    print('')
if choise == 1:
    print('You choise:1(write info in the string)')
    print('')
    print('----------------------------------')
    print('           In the string          ')
    print('')
    print('Hello',name + ',your age is',str(age) + ',you live in',city)
    print('')
    print('Goodbye,see you later:) Have a nice day^^')
    time.sleep(15)
    pass
else:
    print('')
    print('You choise:2(write info in the column)')
    print('')
    print('----------------------------------')
    print('           In the column          ')
    print('')
    print('Hello',name)
    print('Your age',age)
    print('You live in',city)
    print('Goodbye,see you later:) Have a nice day^^')
    time.sleep(15)
    pass
